apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: asd2321s2/posts:0.0.1
        resources:
          limits:
            memory: "20Mi"
            cpu: "300m"
